version: "3.9"
services:
# Nodejs server 
  server:
    image: "node:lts-apline"
    depends_on:
      - mysql
      - keycloak
    build: ./server
    ports:
      - "8087:3001"
    volumes: 
      - ./server:/usr/src/app
  #React-App
  react-app:
    image: node:14
    depends_on:
      - mysql
      - keycloak
      - server
    build: ./react-app
    working_dir: /home/app
    ports:
      - 8086:3000
    volumes:
      - ./react-app/src:/home/app/src
      - ./react-app/public:/home/app/public
    command: npm start
  mysql:
    image: mysql:latest
    ports:
      - 8088:3306
    volumes:
      - ./test-sql-2:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=mysql_db
      - MYSQL_USER=node_server
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=pwd
  keycloak:
    image: jboss/keycloak:latest
    build: ./keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: mysql_db
      DB_USER: node_server
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8089:8080
      - 8090:8443
    depends_on:
      - mysql