export const ShopActionTypes = {
    FETCH_ITEMS_START: "FETCH_ITEMS_START",
    FETCH_ITEMS_SUCCESS: "FETCH_ITEMS_SUCCESS",
    FETCH_ITEMS_FAILURE: "FETCH_ITEMS_FAILURE",
    RESET_ITEMS_SUCCESS: "RESET_ITEMS_SUCCESS",
    FETCH_ITEMS_FOR_CLIENT_START: "FETCH_ITEMS_FOR_CLIENT_START",
    FETCH_ITEMS_FOR_CLIENT_SUCCESS: "FETCH_ITEMS_FOR_CLIENT_SUCCESS",
    FETCH_ITEMS_FOR_CLIENT_FAILURE: "FETCH_ITEMS_FOR_CLIENT_FAILURE",
    SET_SEARCH_ITEMS: "SET_SEARCH_ITEMS",
    };