export const StructureActionTypes = {
    SET_SHOPPER_STATE: "SET_SHOPPER_STATE",
    SET_APP_STATE: "SET_APP_STATE",
    SET_CLIENT_STATE: "SET_CLIENT_STATE",
    SET_USER_NAME: "SET_USER_NAME",
    SET_USER: "SET_USER",
    SET_USER_ERROR: "SET_USER_ERROR",
  };

