export const AppStates = {
    CHOICE: "CHOICE",
    CLIENT: "CLIENT",
    SHOPPER: "SHOPPER",
    PROFILE: "PROFILE"
};
export const ShopperStates = {
    AVAILABLE_DELIVERIES: "AVAILABLE_DELIVERIES",
    ACCEPTED_DELIVERIES: "ACCEPTED_DELIVERIES",
    AVAILABLE_DEIVERIES_SHOP: "AVAILABLE_DEIVERIES_SHOP"
};

export const ClientStates = {
    MY_DELIVERY: "MY_DELIVERY",
    CREATE_DELIVERY: "CREATE_DELIVERY",
    SHOP_CREATE_DELIVERY: "SHOP_CREATE_DELIVERY",
    SHOP_CONFIRM_LIST: "SHOP_CONFIRM_LIST",
    CONFIRM_LIST: "CONFIRM_LIST",
    CREATION_CHOICE: "CREATION_CHOICE"
};